apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: backend
  labels:
    app: backend-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
        version: v1
    spec:
      containers:
      - name: backend
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: backend-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Sentinel Backend Service</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background-color: #f0f8ff; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { color: #2c3e50; text-align: center; margin-bottom: 30px; }
            .info { background: #ecf0f1; padding: 15px; border-radius: 5px; margin: 10px 0; }
            .status { color: #27ae60; font-weight: bold; }
            .warning { color: #e74c3c; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="header">🔒 Sentinel Backend Service</h1>
            <div class="info">
                <h3>Service Information</h3>
                <p><strong>Cluster:</strong> Backend EKS Cluster</p>
                <p><strong>Namespace:</strong> backend</p>
                <p><strong>Service Type:</strong> Internal Only</p>
                <p><strong>Status:</strong> <span class="status">✅ Running</span></p>
            </div>
            <div class="info">
                <h3>Security Status</h3>
                <p class="warning">⚠️ This service is NOT accessible from the internet</p>
                <p>✅ Only accessible from Gateway VPC (10.0.0.0/16)</p>
                <p>✅ Protected by Network Policies</p>
                <p>✅ Running in private subnets</p>
            </div>
            <div class="info">
                <h3>Request Information</h3>
                <p><strong>Timestamp:</strong> <span id="timestamp"></span></p>
                <p><strong>Server:</strong> Backend Pod</p>
            </div>
        </div>
        <script>
            document.getElementById('timestamp').textContent = new Date().toISOString();
        </script>
    </body>
    </html>
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
